// priority: 0
ServerEvents.recipes(event => {
	// stairs
	function stair(inputItem, resultItem) {
		event.shaped(Item.of(resultItem,3), ['A ', 'AA'], {A: inputItem})
	}
	stair('twigs:bamboo_thatch','kubejs:bamboo_thatch_stairs')
	stair('kubejs:straw_thatch','kubejs:straw_thatch_stairs')
	stair('kubejs:flax_thatch','kubejs:flax_thatch_stairs')
	stair('kubejs:deepslate_gravel_bricks','kubejs:deepslate_gravel_brick_stairs')
	stair('kubejs:blackstone_gravel_bricks','kubejs:blackstone_gravel_brick_stairs')
	stair('kubejs:cobbled_blackstone','kubejs:cobbled_blackstone_stairs')
	stair('kubejs:lachryte','kubejs:lachryte_stairs')
	stair('kubejs:polished_lachryte','kubejs:polished_lachryte_stairs')
	stair('kubejs:lachryte_bricks','kubejs:lachryte_brick_stairs')
	stair('emerald_block','kubejs:lapis_stairs')
	stair('spelunkery:rough_lazurite_block','kubejs:lazurite_stairs')
	stair('oreganized:polished_glance','oreganized:polished_glance_stairs')
	stair('smooth_stone','kubejs:smooth_stone_stairs')
	stair('kubejs:exolite','architects_palette:myonite_stairs')
	stair('kubejs:cobbled_exolite','architects_palette:myonite_brick_stairs')
	stair('architects_palette:unobtanium_block','kubejs:enigmatic_tile_stairs')
	
	stair('sandstone','sandstone_stairs')
	stair('quark:sandstone_bricks','quark:sandstone_bricks_stairs')
	stair('kubejs:polished_sandstone','kubejs:polished_sandstone_stairs')
	stair('kubejs:sandstone_tiles','kubejs:sandstone_tile_stairs')
	stair('red_sandstone','red_sandstone_stairs')
	stair('quark:red_sandstone_bricks','quark:red_sandstone_bricks_stairs')
	stair('kubejs:polished_red_sandstone','kubejs:polished_red_sandstone_stairs')
	stair('kubejs:red_sandstone_tiles','kubejs:red_sandstone_tile_stairs')
	stair('quark:soul_sandstone','quark:soul_sandstone_stairs')
	stair('quark:soul_sandstone_bricks','quark:soul_sandstone_bricks_stairs')
	stair('kubejs:polished_soul_sandstone','kubejs:polished_soul_sandstone_stairs')
	stair('kubejs:soul_sandstone_tiles','kubejs:soul_sandstone_tile_stairs')
	
	// slabs
	function slab(inputItem, resultItem) {
		event.shaped(Item.of(resultItem,4), ['AA'], {A: inputItem})
		event.shaped(Item.of(inputItem), ['A', 'A'], {A: resultItem})
	}
	slab('kubejs:straw_thatch','kubejs:straw_thatch_slab')
	slab('kubejs:flax_thatch','kubejs:flax_thatch_slab')
	slab('kubejs:lachryte','kubejs:lachryte_slab')
	slab('kubejs:polished_lachryte','kubejs:polished_lachryte_slab')
	slab('kubejs:lachryte_bricks','kubejs:lachryte_brick_slab')
	slab('kubejs:deepslate_gravel_bricks','kubejs:deepslate_gravel_brick_slab')
	slab('kubejs:blackstone_gravel_bricks','kubejs:blackstone_gravel_brick_slab')
	slab('kubejs:cobbled_blackstone','kubejs:cobbled_blackstone_slab')
	slab('emerald_block','kubejs:lapis_slab')
	slab('spelunkery:rough_lazurite_block','kubejs:lazurite_slab')
	slab('oreganized:polished_glance','oreganized:polished_glance_slab')
	slab('kubejs:exolite','architects_palette:myonite_slab')
	slab('kubejs:cobbled_exolite','architects_palette:myonite_brick_slab')
	slab('architects_palette:unobtanium_block','kubejs:enigmatic_tile_slab')
	
	slab('sandstone','sandstone_slab')
	slab('cut_sandstone','cut_sandstone_slab')
	slab('quark:sandstone_bricks','quark:sandstone_bricks_slab')
	slab('kubejs:polished_sandstone','kubejs:polished_sandstone_slab')
	slab('kubejs:sandstone_tiles','kubejs:sandstone_tile_slab')
	slab('red_sandstone','red_sandstone_slab')
	slab('cut_red_sandstone','cut_red_sandstone_slab')
	slab('quark:red_sandstone_bricks','quark:red_sandstone_bricks_slab')
	slab('kubejs:polished_red_sandstone','kubejs:polished_red_sandstone_slab')
	slab('kubejs:red_sandstone_tiles','kubejs:red_sandstone_tile_slab')
	slab('quark:soul_sandstone','quark:soul_sandstone_slab')
	slab('quark:cut_soul_sandstone','quark:cut_soul_sandstone_slab')
	slab('quark:soul_sandstone_bricks','quark:soul_sandstone_bricks_slab')
	slab('kubejs:polished_soul_sandstone','kubejs:polished_soul_sandstone_slab')
	slab('kubejs:soul_sandstone_tiles','kubejs:soul_sandstone_tile_slab')
	
	// walls
	function wall(inputItem, resultItem) {
		event.shaped(Item.of(resultItem,6), ['AAA'], {A: inputItem})
		event.shaped(Item.of(inputItem), ['A', 'A'], {A: resultItem})
	}
	wall('kubejs:lachryte','kubejs:lachryte_wall')
	wall('kubejs:polished_lachryte','kubejs:polished_lachryte_wall')
	wall('kubejs:lachryte_bricks','kubejs:lachryte_brick_wall')
	wall('kubejs:deepslate_gravel_bricks','kubejs:deepslate_gravel_brick_wall')
	wall('kubejs:blackstone_gravel_bricks','kubejs:blackstone_gravel_brick_wall')
	wall('kubejs:cobbled_blackstone','kubejs:cobbled_blackstone_wall')
	wall('emerald_block','kubejs:lapis_wall')
	wall('spelunkery:rough_lazurite_block','kubejs:lazurite_wall')
	wall('smooth_stone','kubejs:smooth_stone_wall')
	wall('kubejs:exolite','architects_palette:myonite_wall')
	wall('kubejs:cobbled_exolite','architects_palette:myonite_brick_wall')
	wall('architects_palette:unobtanium_block','kubejs:enigmatic_tile_wall')
	
	wall('sandstone','sandstone_wall')
	wall('quark:sandstone_bricks','quark:sandstone_bricks_wall')
	wall('kubejs:polished_sandstone','kubejs:polished_sandstone_wall')
	wall('kubejs:sandstone_tiles','kubejs:sandstone_tile_wall')
	wall('red_sandstone','red_sandstone_wall')
	wall('quark:red_sandstone_bricks','quark:red_sandstone_bricks_wall')
	wall('kubejs:polished_red_sandstone','kubejs:polished_red_sandstone_wall')
	wall('kubejs:red_sandstone_tiles','kubejs:red_sandstone_tile_wall')
	wall('quark:soul_sandstone','quark:soul_sandstone_wall')
	wall('quark:soul_sandstone_bricks','quark:soul_sandstone_bricks_wall')
	wall('kubejs:polished_soul_sandstone','kubejs:polished_soul_sandstone_wall')
	wall('kubejs:soul_sandstone_tiles','kubejs:soul_sandstone_tile_wall')
	
	// pillars
	function pillar(inputItem, resultItem) {
		event.shaped(Item.of(resultItem,2), ['A', 'A'], {A: inputItem})
	}
	pillar('purpur_block','purpur_pillar')
	pillar('quark:midori_block','quark:midori_pillar')
	pillar('quark:iron_plate','quark:iron_pillar')
	pillar('polished_granite','quark:granite_pillar')
	pillar('polished_diorite','quark:diorite_pillar')
	pillar('polished_andesite','quark:andesite_pillar')
	pillar('quark:polished_dripstone','quark:dripstone_pillar')
	pillar('quark:polished_calcite','quark:calcite_pillar')
	pillar('quark:polished_tuff','quark:tuff_pillar')
	pillar('oreganized:polished_glance','kubejs:glance_pillar')
	pillar('smooth_basalt','basalt')
	pillar('paletteblocks:polished_basalt','polished_basalt')
	
	pillar('sandstone','kubejs:sandstone_pillar')
	pillar('red_sandstone','kubejs:red_sandstone_pillar')
	pillar('quark:soul_sandstone','kubejs:soul_sandstone_pillar')
	
	// shingles
	function shingle(inputItem, resultItem) {
		event.shaped(Item.of(resultItem,6), ['AAA', 'AAA'], {A: inputItem})
	}
	shingle('terracotta','quark:shingles')
	shingle('twigs:packed_silt','twigs:silt_shingles')
	shingle('sullysmod:polished_jade_block','sullysmod:polished_jade_shingles')
	shingle('copper_block','create:copper_shingles')
	shingle('exposed_copper','create:exposed_copper_shingles')
	shingle('weathered_copper','create:weathered_copper_shingles')
	shingle('oxidized_copper','create:oxidized_copper_shingles')
	
	// bookshelves
	function bookshelf(inputItem, resultItem) {
		event.shaped(Item.of(resultItem,3), ['AAA', 'BBB', 'AAA'], {A: inputItem, B: 'book'})
	}
	bookshelf('quark:bamboo_planks','quark:bamboo_bookshelf')
	bookshelf('mynethersdelight:powdery_planks','everycomp:q/mynethersdelight/powdery_bookshelf')
	bookshelf('architects_palette:twisted_planks','everycomp:q/architects_palette/twisted_bookshelf')
	bookshelf('ecologics:azalea_planks','everycomp:q/ecologics/azalea_bookshelf')
	bookshelf('ecologics:coconut_planks','everycomp:q/ecologics/coconut_bookshelf')
	
	// deploy waxing
	function deployWaxing(inputItem, resultItem) {
		event.recipes.create.deploying(resultItem, [inputItem, 'honeycomb_block']).keepHeldItem()
	}
	deployWaxing('kubejs:copper_pillar', 'kubejs:waxed_copper_pillar')
	deployWaxing('kubejs:exposed_copper_pillar', 'kubejs:waxed_exposed_copper_pillar')
	deployWaxing('kubejs:weathered_copper_pillar', 'kubejs:waxed_weathered_copper_pillar')
	deployWaxing('kubejs:oxidized_copper_pillar', 'kubejs:waxed_oxidized_copper_pillar')
	deployWaxing('copperandtuffbackport:chiseled_copper', 'copperandtuffbackport:waxed_chiseled_copper')
	deployWaxing('copperandtuffbackport:exposed_chiseled_copper', 'copperandtuffbackport:waxed_exposed_chiseled_copper')
	deployWaxing('copperandtuffbackport:weathered_chiseled_copper', 'copperandtuffbackport:waxed_weathered_chiseled_copper')
	deployWaxing('copperandtuffbackport:oxidized_chiseled_copper', 'copperandtuffbackport:waxed_oxidized_chiseled_copper')
	deployWaxing('copperandtuffbackport:copper_door', 'copperandtuffbackport:waxed_copper_door')
	deployWaxing('copperandtuffbackport:exposed_copper_door', 'copperandtuffbackport:waxed_exposed_copper_door')
	deployWaxing('copperandtuffbackport:weathered_copper_door', 'copperandtuffbackport:waxed_weathered_copper_door')
	deployWaxing('copperandtuffbackport:oxidized_copper_door', 'copperandtuffbackport:waxed_oxidized_copper_door')
	deployWaxing('copperandtuffbackport:copper_trapdoor', 'copperandtuffbackport:waxed_copper_trapdoor')
	deployWaxing('copperandtuffbackport:exposed_copper_trapdoor', 'copperandtuffbackport:waxed_exposed_copper_trapdoor')
	deployWaxing('copperandtuffbackport:weathered_copper_trapdoor', 'copperandtuffbackport:waxed_weathered_copper_trapdoor')
	deployWaxing('copperandtuffbackport:oxidized_copper_trapdoor', 'copperandtuffbackport:waxed_oxidized_copper_trapdoor')
	deployWaxing('copperandtuffbackport:copper_grate', 'copperandtuffbackport:waxed_copper_grate')
	deployWaxing('copperandtuffbackport:exposed_copper_grate', 'copperandtuffbackport:waxed_exposed_copper_grate')
	deployWaxing('copperandtuffbackport:weathered_copper_grate', 'copperandtuffbackport:waxed_weathered_copper_grate')
	deployWaxing('copperandtuffbackport:oxidized_copper_grate', 'copperandtuffbackport:waxed_oxidized_copper_grate')
	deployWaxing('copperandtuffbackport:copper_bulb', 'copperandtuffbackport:waxed_copper_bulb')
	deployWaxing('copperandtuffbackport:exposed_copper_bulb', 'copperandtuffbackport:waxed_exposed_copper_bulb')
	deployWaxing('copperandtuffbackport:weathered_copper_bulb', 'copperandtuffbackport:waxed_weathered_copper_bulb')
	deployWaxing('copperandtuffbackport:oxidized_copper_bulb', 'copperandtuffbackport:waxed_oxidized_copper_bulb')
	deployWaxing('copperized:medium_weighted_pressure_plate', 'copperized:waxed_medium_weighted_pressure_plate')
	deployWaxing('copperized:exposed_medium_weighted_pressure_plate', 'copperized:waxed_exposed_medium_weighted_pressure_plate')
	deployWaxing('copperized:weathered_medium_weighted_pressure_plate', 'copperized:waxed_weathered_medium_weighted_pressure_plate')
	deployWaxing('copperized:oxidized_medium_weighted_pressure_plate', 'copperized:waxed_oxidized_medium_weighted_pressure_plate')
	deployWaxing('caverns_and_chasms:floodlight', 'caverns_and_chasms:waxed_floodlight')
	deployWaxing('caverns_and_chasms:exposed_floodlight', 'caverns_and_chasms:waxed_exposed_floodlight')
	deployWaxing('caverns_and_chasms:weathered_floodlight', 'caverns_and_chasms:waxed_weathered_floodlight')
	deployWaxing('caverns_and_chasms:oxidized_floodlight', 'caverns_and_chasms:waxed_oxidized_floodlight')
	deployWaxing('caverns_and_chasms:copper_bars', 'caverns_and_chasms:waxed_copper_bars')
	deployWaxing('caverns_and_chasms:exposed_copper_bars', 'caverns_and_chasms:waxed_exposed_copper_bars')
	deployWaxing('caverns_and_chasms:weathered_copper_bars', 'caverns_and_chasms:waxed_weathered_copper_bars')
	deployWaxing('caverns_and_chasms:oxidized_copper_bars', 'caverns_and_chasms:waxed_oxidized_copper_bars')
	deployWaxing('caverns_and_chasms:copper_button', 'caverns_and_chasms:waxed_copper_button')
	deployWaxing('caverns_and_chasms:exposed_copper_button', 'caverns_and_chasms:waxed_exposed_copper_button')
	deployWaxing('caverns_and_chasms:weathered_copper_button', 'caverns_and_chasms:waxed_weathered_copper_button')
	deployWaxing('caverns_and_chasms:oxidized_copper_button', 'caverns_and_chasms:waxed_oxidized_copper_button')
	deployWaxing('lightning_rod', 'caverns_and_chasms:waxed_lightning_rod')
	deployWaxing('caverns_and_chasms:exposed_lightning_rod', 'caverns_and_chasms:waxed_exposed_lightning_rod')
	deployWaxing('caverns_and_chasms:weathered_lightning_rod', 'caverns_and_chasms:waxed_weathered_lightning_rod')
	deployWaxing('caverns_and_chasms:oxidized_lightning_rod', 'caverns_and_chasms:waxed_oxidized_lightning_rod')
	deployWaxing('mynethersdelight:hoglin_trophy', 'mynethersdelight:waxed_hoglin_trophy')
})